image: node:20

stages:
  - build
  - deploy

cache:
  paths:
    - node_modules/

before_script:
  - npm ci

build:
  stage: build
  script:
    - npx prisma generate
    - npx prisma migrate deploy
    - npm run build
    - apt-get update && apt-get install -y zip
    - zip -r dist.zip dist prisma package.json package-lock.json
  artifacts:
    paths:
      - dist.zip
    expire_in: 1 hour

deploy:
  image: mcr.microsoft.com/azure-cli
  stage: deploy
  dependencies:
    - build
  before_script: []
  script:
    - echo "$AZURE_CREDENTIALS" > creds.json

    - CLIENT_ID=$(jq -r .clientId creds.json)
    - CLIENT_SECRET=$(jq -r .clientSecret creds.json)
    - TENANT_ID=$(jq -r .tenantId creds.json)
    - SUBSCRIPTION_ID=$(jq -r .subscriptionId creds.json)

    - az login --service-principal --username "$CLIENT_ID" --password "$CLIENT_SECRET" --tenant "$TENANT_ID"
    - az account set --subscription "$SUBSCRIPTION_ID"

    - az webapp deploy --resource-group Interlux_group --name Interlux --src-path dist.zip --type zip
