stages:
  - deploy

deploy-backend:
  image: mcr.microsoft.com/azure-cli
  stage: deploy
  script:
    - echo "$AZURE_CREDENTIALS" > creds.json

    - CLIENT_ID=$(jq -r .clientId creds.json)
    - CLIENT_SECRET=$(jq -r .clientSecret creds.json)
    - TENANT_ID=$(jq -r .tenantId creds.json)
    - SUBSCRIPTION_ID=$(jq -r .subscriptionId creds.json)

    - az login --service-principal --username "$CLIENT_ID" --password "$CLIENT_SECRET" --tenant "$TENANT_ID"
    - az account set --subscription "$SUBSCRIPTION_ID"

    - az webapp deploy --resource-group Interlux_group --name Interlux --src-path ./dist.zip --type zip
  only:
    - main
